# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        # news section
        ROLE_NEWS_SECTION_CRUD:
            - ROLE_NEWS_SECTION_CREATE
            - ROLE_NEWS_SECTION_UPDATE
            - ROLE_NEWS_SECTION_DELETE
        ROLE_NEWS_ARTICLE_CRUD:
            - ROLE_NEWS_ARTICLE_CREATE
            - ROLE_NEWS_ARTICLE_UPDATE
            - ROLE_NEWS_ARTICLE_DELETE
        #g
        ROLE_NEWS_CRUD:
            - ROLE_NEWS_SECTION_CRUD
            - ROLE_NEWS_ARTICLE_CRUD
        # -- news section

        # university
        ROLE_UNI_ARTICLE_CRUD:
            - ROLE_UNI_ARTICLE_CREATE
            - ROLE_UNI_ARTICLE_UPDATE
            - ROLE_UNI_ARTICLE_DELETE
        ROLE_UNI_BOOK_CRUD:
            - ROLE_UNI_BOOK_CREATE
            - ROLE_UNI_BOOK_UPDATE
            - ROLE_UNI_BOOK_DELETE
        ROLE_UNI_EVENT_CRUD:
            - ROLE_UNI_EVENT_CREATE
            - ROLE_UNI_EVENT_UPDATE
            - ROLE_UNI_EVENT_DELETE
        ROLE_UNI_SECTION_CRUD:
            - ROLE_UNI_SECTION_CREATE
            - ROLE_UNI_SECTION_UPDATE
            - ROLE_UNI_SECTION_DELETE
        #g
        ROLE_UNI_CRUD:
            - ROLE_UNI_EVENT_CRUD
            - ROLE_UNI_SECTION_CRUD
            - ROLE_UNI_ARTICLE_CRUD
            - ROLE_UNI_BOOK_CRUD
        # -- university

        # comments
        ROLE_COMMENTS_CRUD:
            - ROLE_COMMENTS_CREATE
            - ROLE_COMMENTS_UPDATE
            - ROLE_COMMENTS_DELETE
        # -- comments
        ROLE_EXPERT:

        ROLE_USER:
            - ROLE_COMMENTS_CRUD
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_EXPERT
            - ROLE_NEWS_CRUD
            - ROLE_UNI_CRUD
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        test:
            pattern: ^/api                               # All URLs are protected
            fos_oauth: true                            # OAuth2 protected resource
            stateless: true                            # Do no set session cookies
            anonymous: true                           # Anonymous access is not allowed
        main:
            pattern: ^/
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html