<?php

namespace UniversityBundle\Repository;

/**
 * BookSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
