<?php

namespace UniversityBundle\Repository;

/**
 * SectionArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
